name: rec_to_nwb
channels:
  - conda-forge
  - defaults
  - franklab
  - novelakrk
dependencies:
  - python>=3.6,<3.10
  - rec_to_binaries
  - pip
  - hdmf>=3.1.1,<4
  - pynwb>=2.0.0,<3
  - asn1crypto
  - blas
  - ca-certificates
  - certifi
  - cffi
  - chardet
  - cryptography
  - elementpath
  - h5py<4
  - hdf5
  - idna
  - libblas
  - libcblas
  - liblapack
  - mkl
  - mkl-service
  - numpy
  - openssl
  - pandas
  - pycparser
  - pyopenssl
  - pysocks
  - python-dateutil
  - pytz
  - requests
  - scipy
  - setuptools
  - six
  - sqlite
  - urllib3
  - wheel
  - xmlschema
  - zlib
  - vdom
  - pyyaml
  - pytest
  - testfixtures
  - jupyterlab
  - nb_conda
  - mountainlab_pytools
  - xmldiff
  - pip:
      - git+git://github.com/LorenFrankLab/ndx-franklab-novela@0.1.0

#  Docs
  - recommonmark
  - sphinx-autoapi
  - sphinx_rtd_theme
