name: lfdatamigration
channels:
  - conda-forge
  - defaults
  - novelakrk
dependencies:
  - asn1crypto=1.3.0=py37_0
  - blas=1.0=mkl
  - ca-certificates=2020.1.1=0
  - certifi=2019.11.28=py37_0
  - cffi=1.13.2=py37hb32ad35_0
  - chardet=3.0.4=py37_1003
  - cryptography=2.8=py37hb32ad35_1
  - elementpath=1.4.1=py_0
  - h5py=2.10.0=nompi_py37h422b98e_102
  - hdf5=1.10.5=nompi_ha405e13_1104
  - hdmf=1.3.3=py_0
  - idna=2.9=py_1
  - libblas=3.8.0=14_mkl
  - libcblas=3.8.0=14_mkl
  - liblapack=3.8.0=14_mkl
  - mkl=2019.4=245
  - mountainlab_pytools=0.7.5=py37_2
  - numpy=1.18.1=py37hc71023c_0
  - openssl=1.1.1d=he774522_4
  - pandas=1.0.1=py37he350917_0
  - pip=20.0.2=py_2
  - pycparser=2.19=py_2
  - pynwb=1.1.2=py_1
  - pyopenssl=19.1.0=py_1
  - pysocks=1.7.1=py37_0
  - python=3.7.4=h5263a28_0
  - python-dateutil=2.8.0=py_0
  - pytz=2019.3=py_0
  - requests=2.23.0=py37_0
  - scipy=1.3.1=py37h29ff71c_0
  - setuptools=45.2.0=py37_0
  - six=1.14.0=py37_0
  - sqlite=3.30.1=hfa6e2cd_0
  - testfixtures=6.14.0=py_0
  - urllib3=1.25.7=py37_0
  - vdom=0.6=py_0
  - xmlschema=1.1.1=py_0
  - yaml=0.2.2=hfa6e2cd_1
  - zlib=1.2.11=h2fa13f4_1006
  - pip:
    - ndx-lflab-novela==0.0.1
    - pdoc==0.3.2
    - rec-to-binaries==0.3.0.dev0
    - xmldiff==2.4
