name: LorenFranksDataMigration
channels:
  - conda-forge
  - defaults
  - novelakrk
dependencies:
  - asn1crypto
  - blas
  - ca-certificates
  - certifi
  - cffi
  - chardet
  - cryptography
  - elementpath
  - h5py
  - hdf5
  - hdmf
  - idna
  - libblas
  - libcblas
  - liblapack
  - mkl
  - mkl-service
  - numpy
  - openssl
  - pandas
  - pip
  - pycparser
  - pynwb
  - pyopenssl
  - pysocks
  - python=3.7.4
  - python-dateutil
  - pytz
  - requests
  - ruamel.yaml
  - ruamel.yaml.clib
  - scipy
  - setuptools
  - six
  - sqlite
  - urllib3
  - wheel
  - xmlschema
  - zlib
  - rec_to_binaries
  - flatiron::mountainlab_pytools


